### ISSUE TITLE
sound based on being silent or not ??

### ISSUE THREAD

**Issue by alialki** [pkuecuekyan/Movieplaying#1]
great video player i am trying to add it to my project but what i was wondering is there anyway to make  the sound always work because while my phone is in silent mode i have no sound if i bring it out of silent mode the sound comes back is there a way to make this happen ?

**Comment by pkuecuekyan** [comment]
New property (shouldPlayAudioOnVibrate) added that allows to override mute/silent (i.e., when phone is set to vibrate.)
